from __future__ import annotations

import os
from concurrent.futures import Future, ThreadPoolExecutor, wait
from dataclasses import dataclass
from pathlib import Path
from time import monotonic
from typing import Any

from .cache import AnalysisCache, content_fingerprint
from .parser_plugins import ParseResult, ParserRegistry

GENERATED_MARKERS = (
    "code generated", "generated file", "auto-generated", "autogenerated",
    "automatically generated", "do not edit", "do not modify",
)


@dataclass(slots=True)
class ParsedFile:
    path: str
    imports: list[Any]
    symbols: list[Any]
    calls: list[Any]
    line_count: int
    complexity: int
    parse_error: str | None
    generated: bool
    skipped_large: bool = False
    skipped_generated: bool = False


def _read_bytes(path: Path, max_bytes: int) -> tuple[bytes | None, str | None]:
    try:
        size = path.stat().st_size
        if size > max_bytes:
            return None, f"file exceeds max parse size ({max_bytes} bytes)"
        return path.read_bytes(), None
    except OSError as exc:
        return None, str(exc)


def _is_generated(content: bytes) -> bool:
    lines = content[:8192].decode("utf-8", errors="ignore").splitlines()[:16]
    comment_prefixes = ("#", "//", "/*", "*", "<!--", ";", "--")
    for line in lines:
        stripped = line.strip().lower()
        if stripped.startswith(comment_prefixes) and any(marker in stripped for marker in GENERATED_MARKERS):
            return True
    return False


def parse_one(
    *,
    root: Path,
    relative: Path,
    component: str,
    module_name: str,
    registry: ParserRegistry,
    cache: AnalysisCache,
    max_parse_bytes: int,
    skip_generated: bool,
) -> ParsedFile:
    absolute = root / relative
    rel_string = relative.as_posix()
    content, read_error = _read_bytes(absolute, max_parse_bytes)
    if read_error:
        return ParsedFile(rel_string, [], [], [], 0, 0, read_error, False, "exceeds" in read_error, False)
    assert content is not None
    generated = _is_generated(content)
    if generated and skip_generated:
        cache.mark_seen(rel_string)
        return ParsedFile(rel_string, [], [], [], 0, 0, "generated file skipped", True, False, True)

    language = registry.language_for(absolute)
    parser_identity = registry.parser_identity(absolute)
    fingerprint = content_fingerprint(
        content,
        language=language,
        module_name=module_name,
        component=component,
        parser_identity=parser_identity,
    )
    cached = cache.get(rel_string, fingerprint)
    if cached is not None:
        imports, symbols, calls, line_count, complexity = cached
        return ParsedFile(rel_string, imports, symbols, calls, line_count, complexity, None, generated)

    text = content.decode("utf-8", errors="replace")
    line_count = len(text.splitlines())
    try:
        result: ParseResult = registry.parse(absolute, text, module_name, rel_string, component)
        cache.put(rel_string, fingerprint, result.imports, result.symbols, result.calls, line_count, result.complexity)
        return ParsedFile(rel_string, result.imports, result.symbols, result.calls, line_count, result.complexity, None, generated)
    except (SyntaxError, ValueError, UnicodeError) as exc:
        return ParsedFile(rel_string, [], [], [], line_count, 0, f"parse error: {exc}", generated)


def parse_files(
    *,
    root: Path,
    candidates: list[Path],
    file_component: dict[str, str],
    module_name_by_file: dict[str, str],
    registry: ParserRegistry,
    cache: AnalysisCache,
    max_parse_bytes: int,
    skip_generated: bool,
    workers: int,
    deadline: float | None,
) -> tuple[dict[str, ParsedFile], int, bool]:
    resolved_workers = workers if workers > 0 else min(32, max(1, (os.cpu_count() or 1) + 4))
    if deadline is not None:
        resolved_workers = 1
    parsed: dict[str, ParsedFile] = {}
    time_budget_exceeded = False

    if resolved_workers == 1:
        for relative in candidates:
            if deadline is not None and monotonic() >= deadline:
                time_budget_exceeded = True
                break
            rel_string = relative.as_posix()
            parsed[rel_string] = parse_one(
                root=root, relative=relative, component=file_component[rel_string],
                module_name=module_name_by_file[rel_string], registry=registry, cache=cache,
                max_parse_bytes=max_parse_bytes, skip_generated=skip_generated,
            )
        return parsed, resolved_workers, time_budget_exceeded

    with ThreadPoolExecutor(max_workers=resolved_workers, thread_name_prefix="perspector") as executor:
        futures: dict[Future[ParsedFile], str] = {}
        for relative in candidates:
            rel_string = relative.as_posix()
            futures[executor.submit(
                parse_one,
                root=root, relative=relative, component=file_component[rel_string],
                module_name=module_name_by_file[rel_string], registry=registry, cache=cache,
                max_parse_bytes=max_parse_bytes, skip_generated=skip_generated,
            )] = rel_string
        done, _ = wait(futures)
        for future in done:
            rel_string = futures[future]
            try:
                parsed[rel_string] = future.result()
            except Exception as exc:
                parsed[rel_string] = ParsedFile(rel_string, [], [], [], 0, 0, f"parser worker failed: {exc}", False)
    return parsed, resolved_workers, time_budget_exceeded
